extends:
  - ./.eslintrc.custom.yml
ignorePatterns:
  - test/webDriver/static/**
overrides:
  - env:
      commonjs: true
    files:
      - '**/*.cjs'
      - '**/*.js'
    rules:
      import/no-commonjs: off
  - files:
      - '**/*.mjs'
    parserOptions:
      ecmaVersion: latest
      sourceType: module
